import { useEffect, useState } from 'react'
import { Activity, CheckCircle2, CloudRain, Download, Droplets, ExternalLink, FlaskConical, Gauge, HeartPulse, Leaf, Moon, RefreshCw, ShieldCheck, Sun, ThermometerSun, Wind } from 'lucide-react'
import { getLiveOverview, getLocations, getModelManifest, getSubmissionStatus, SUBMISSION_DOWNLOAD_URL, SUBMISSION_EXAMPLE_URL, SUBMISSION_PARTIAL_URL } from './api'
import type { LiveOverview, LocationOption, ModelManifest, SubmissionStatus } from './types'
import './styles.css'
import './context.css'
import './research.css'

const weatherLabel = (code: number | null | undefined) => code == null ? 'Condição indisponível' : code === 0 ? 'Céu limpo' : code <= 3 ? 'Parcialmente nublado' : code <= 48 ? 'Névoa' : code <= 67 ? 'Chuva' : code <= 82 ? 'Pancadas de chuva' : code <= 99 ? 'Trovoadas' : 'Condição variável'
const format = (value: number | null | undefined, unit = '', digits = 1) => value == null ? 'Indisponível' : `${value.toLocaleString('pt-BR', { maximumFractionDigits: digits })}${unit}`
const aqiLabel = (value: number | null) => value == null ? 'Sem leitura' : value <= 50 ? 'Boa' : value <= 100 ? 'Moderada' : value <= 150 ? 'Atenção a sensíveis' : value <= 200 ? 'Ruim' : 'Muito ruim'

export default function App() {
  const [locations, setLocations] = useState<LocationOption[]>([])
  const [location, setLocation] = useState('brasilia')
  const [data, setData] = useState<LiveOverview | null>(null)
  const [model, setModel] = useState<ModelManifest | null>(null)
  const [submission, setSubmission] = useState<SubmissionStatus | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [refreshKey, setRefreshKey] = useState(0)
  useEffect(() => { const controller = new AbortController(); getLocations(controller.signal).then(setLocations).catch(() => undefined); getModelManifest(controller.signal).then(setModel).catch(() => undefined); getSubmissionStatus(controller.signal).then(setSubmission).catch(() => undefined); return () => controller.abort() }, [])
  useEffect(() => { const controller = new AbortController(); getLiveOverview(location, controller.signal).then(setData).catch((requestError: Error) => { if (requestError.name !== 'AbortError') setError(requestError.message) }).finally(() => { if (!controller.signal.aborted) setLoading(false) }); return () => controller.abort() }, [location, refreshKey])
  const refresh = () => { setLoading(true); setError(''); setRefreshKey((key) => key + 1) }
  const changeLocation = (nextLocation: string) => { setLoading(true); setError(''); setLocation(nextLocation) }
  const current = data?.current
  const air = data?.air_quality
  const oni = data?.climate_context?.oni
  const astronomy = data?.astronomy
  return <main>
    <header className="topbar"><a href="#agora" className="brand"><span><CloudRain size={22} /></span>CLIMA<strong>ZOIDE</strong></a><div className="top-actions"><span className={`live-pill ${error ? 'live-pill--error' : ''}`}><i />{loading ? 'Atualizando contexto' : error ? 'Fonte indisponível' : 'Contexto operacional recente'}</span><button onClick={refresh} disabled={loading}><RefreshCw size={15} /> Atualizar contexto</button></div></header>
    <section className="hero" id="agora"><div><p className="eyebrow">Inteligência climática para a América do Sul</p><h1>O clima muda.<br /><em>Sua decisão acompanha.</em></h1><p className="lede">Tempo, chuva, ar, solo e impactos reunidos em uma leitura objetiva, alimentada por fontes nacionais e internacionais.</p></div><div className="location-control"><label htmlFor="location">Ponto operacional</label><select id="location" value={location} onChange={(event) => changeLocation(event.target.value)}>{(locations.length ? locations : [{ id: 'brasilia', name: 'Brasília', country: 'Brasil', code: 'BR', state: 'DF', latitude: 0, longitude: 0 }]).map((item) => <option key={item.id} value={item.id}>{item.name} · {item.code}</option>)}</select><small>{data ? `${data.location.country} · ${data.location.latitude.toFixed(4)}, ${data.location.longitude.toFixed(4)} · ${data.timezone}` : 'Conectando ao backend…'}</small></div></section>
    <aside className="temporal-notice"><ShieldCheck size={18} /><div><strong>Camadas separadas</strong><span>O contexto recente abaixo é informativo e não entra na previsão mensal. O contrato científico exige dados disponíveis até o mês anterior; a validação da implementação continua pendente.</span></div></aside>
    {error && !data && <section className="error-state"><CloudRain size={34} /><h2>Não foi possível consultar as fontes agora.</h2><p>{error} Nenhum dado simulado foi exibido. O backend tenta novamente antes de informar indisponibilidade.</p><button onClick={refresh}>Tentar novamente</button></section>}
    {data && <>
      <section className="now-grid" aria-busy={loading}>
        <article className="weather-card primary-card"><div className="card-head"><span>Condição meteorológica em {data.location.name}</span><span className="verified"><ShieldCheck size={14} /> {data.weather_metadata.provider}</span></div><div className="temperature">{format(current?.temperature, '°')}</div><h2>{current?.condition ?? weatherLabel(current?.weather_code)}</h2><p>Valor válido em {current?.observed_at ? new Date(current.observed_at).toLocaleString('pt-BR') : 'horário indisponível'} · fonte: {data.weather_metadata.provider}</p><div className="mini-stats"><span><Droplets /> {format(current?.humidity, '%', 0)}</span><span><Wind /> {format(current?.wind_speed, ' km/h')}</span><span><CloudRain /> {format(current?.precipitation, ' mm')}</span></div></article>
        <article className="weather-card"><div className="card-head"><span>Ar e saúde</span><Activity size={18} /></div><strong className="aqi">{format(air?.us_aqi, '', 0)}</strong><span className="aqi-label">AQI · {aqiLabel(air?.us_aqi ?? null)}</span><div className="air-grid"><span>PM2.5<strong>{format(air?.pm2_5, ' µg/m³')}</strong></span><span>Ozônio<strong>{format(air?.ozone, ' µg/m³')}</strong></span><span>UV agora<strong>{format(air?.uv_index)}</strong></span></div><p>CAMS/Copernicus via Open-Meteo · leitura válida em {air?.observed_at ? new Date(air.observed_at).toLocaleString('pt-BR') : 'horário indisponível'}. Informação ambiental, não orientação médica.</p></article>
        <article className="weather-card"><div className="card-head"><span>Sistema físico</span><Gauge size={18} /></div><div className="system-row"><Droplets /><div><span>Umidade superficial do solo</span><strong>{format(current?.soil_moisture, ' m³/m³', 3)}</strong></div></div><div className="system-row"><Wind /><div><span>Rajadas</span><strong>{format(current?.wind_gusts, ' km/h')}</strong></div></div><div className="system-row"><Gauge /><div><span>Pressão superficial</span><strong>{format(current?.surface_pressure, ' hPa', 0)}</strong></div></div></article>
      </section>
      <section className="coverage-strip" aria-label="Cobertura do projeto"><div><span>Domínio científico</span><strong>{data.coverage.scientific_domain}</strong></div><div><span>Grade oficial</span><strong>{data.coverage.grid_resolution} · {data.coverage.grid_points_per_month.toLocaleString('pt-BR')} pontos/mês</strong></div><div><span>Camada operacional</span><strong>{data.coverage.operational_points} pontos representativos</strong></div><p>{data.coverage.note}</p></section>
      {model && <section className="section-block model-lab"><div className="section-heading"><div><p className="eyebrow">Laboratório científico</p><h2>Modelos e prontidão</h2></div><p>Experimentos e modelos candidatos não são resultados aprovados. O estado é sincronizado com o backend.</p></div><aside className={`audit-callout audit-callout--${model.scientific_audit.status}`} role="status"><ShieldCheck size={20} /><div><strong>{model.scientific_audit.status === 'passed' ? 'Auditoria científica aprovada' : 'Previsão mensal ainda não aprovada'}</strong><p>{model.scientific_audit.summary}</p><small>{model.scientific_audit.rule}</small></div></aside><div className="model-lab-grid"><div className="candidate-grid">{model.candidate_models.map((candidate) => <article key={candidate.id}><FlaskConical /><div><span>{candidate.status === 'ready_for_retraining' ? 'Pronto para retreino' : candidate.status === 'ready_for_training' ? 'Pronto para treino' : candidate.status === 'research_only' ? 'Pesquisa · não aprovado' : 'Não implementado'}</span><h3>{candidate.label}</h3><p>{candidate.purpose}</p></div></article>)}</div><aside><h3>Checklist do modelo</h3>{model.readiness.map((item) => <div className={`readiness readiness--${item.status}`} key={item.id}>{item.status === 'passed' ? <CheckCircle2 /> : <i />}<span>{item.label}</span><strong>{item.status === 'passed' ? 'OK' : item.status === 'blocked_by_auth' ? 'Exige acesso externo' : 'Pendente'}</strong></div>)}</aside></div></section>}
      {submission && <section className="section-block submission-block"><div className="section-heading"><div><p className="eyebrow">Exportação de dados</p><h2>Arquivos do Climazoide</h2></div><p>Formato de previsão: <code>id,tp_mm_day</code>{submission.expected_rows == null ? '. Os meses, IDs e a quantidade de linhas serão definidos pelo arquivo oficial do conjunto de teste.' : `, com ${submission.expected_rows.toLocaleString('pt-BR')} IDs oficiais do conjunto de teste.`}</p></div><div className="submission-panel"><div><span className={submission.ready ? 'submission-ready' : 'submission-pending'}>{submission.ready ? 'Validado e pronto' : 'Ainda não gerado'}</span><h3>CSV completo do projeto</h3><p>{submission.temporal_contract}</p><ul>{submission.blocking_reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul></div><div className="submission-actions">{submission.ready ? <a className="download-primary" href={SUBMISSION_DOWNLOAD_URL}><Download size={16} /> Baixar CSV completo</a> : <button className="download-primary" disabled><Download size={16} /> CSV completo indisponível</button>}{submission.partial_available && <a href={SUBMISSION_PARTIAL_URL}><Download size={16} /> Baixar CSV parcial</a>}<small>{submission.partial_notice}</small><a href={SUBMISSION_EXAMPLE_URL}><Download size={16} /> Baixar exemplo de formato</a><small>O exemplo contém três linhas ilustrativas; não são previsões nem substituem IDs do teste.</small></div></div></section>}
      <section className="section-block"><div className="section-heading"><div><p className="eyebrow">Próximos 7 dias</p><h2>Chuva e temperatura</h2></div><p>Previsão de {data.weather_metadata.provider}. {data.weather_metadata.model_updated_at ? `Modelo atualizado em ${new Date(data.weather_metadata.model_updated_at).toLocaleString('pt-BR')}.` : 'A fonte não informa o horário de atualização do modelo.'} Período válido: {data.weather_metadata.valid_from ?? '—'} a {data.weather_metadata.valid_until ?? '—'}.</p></div><div className="forecast-grid">{data.daily.map((day) => <article key={day.time} className="day-card"><span>{new Date(`${day.time}T12:00:00`).toLocaleDateString('pt-BR', { weekday: 'short', day: '2-digit' })}</span><CloudRain className={(day.precipitation_sum ?? 0) > 1 ? 'rainy' : ''} /><strong>{format(day.temperature_2m_max, '°', 0)} <small>{format(day.temperature_2m_min, '°', 0)}</small></strong><div className="rain-prob"><i style={{ width: `${day.precipitation_probability_max ?? 0}%` }} /></div><small>{format(day.precipitation_sum, ' mm')} · {format(day.precipitation_probability_max, '%', 0)}</small></article>)}</div></section>
      <section className="section-block"><div className="section-heading"><div><p className="eyebrow">Clima conectado à vida</p><h2>Impactos que ajudam a decidir</h2></div><p>Indicadores derivados somente dos dados públicos recebidos.</p></div><div className="impact-grid">{data.impacts.map((impact, index) => { const Icon = [Droplets, Leaf, ThermometerSun, HeartPulse][index] ?? Gauge; return <article key={impact.id}><Icon /><span>{impact.label}</span><strong>{format(impact.value, ` ${impact.unit}`)}</strong><p>{impact.detail}</p></article> })}</div></section>
      <section className="section-block"><div className="section-heading"><div><p className="eyebrow">Contexto de grande escala</p><h2>Oceano, Sol e Lua</h2></div><p>Camadas públicas para contextualizar clima, energia, costa e ciclos naturais.</p></div><div className="context-grid"><article><Moon /><div><span>ENSO · {oni?.season ?? '—'} {oni?.year ?? ''}</span><strong>{oni?.available ? `${format(oni.value, '°C')} · ${oni.phase}` : 'Indisponível'}</strong><p>ONI oficial do NOAA CPC. É contexto oceânico, não previsão local de chuva.</p></div></article><article><Sun /><div><span>Efemérides · UTC</span><strong>{astronomy?.available ? `${astronomy.sunrise_utc} ↑ · ${astronomy.sunset_utc} ↓` : 'Indisponível'}</strong><p>Lua {astronomy?.moon_phase ?? 'sem leitura'} · iluminação {astronomy?.moon_illumination ?? '—'}, USNO.</p></div></article></div></section>
      <section className="section-block"><div className="section-heading"><div><p className="eyebrow">Transparência por padrão</p><h2>Fontes e disponibilidade</h2></div><p>Sem fonte, sem número. Cada integração informa seu estado real.</p></div><div className="source-grid">{data.sources.map((source) => { const outsideScope = source.applicable === false; return <a href={source.url} target="_blank" rel="noreferrer" key={source.name}><span className={source.available ? 'source-ok' : 'source-off'}>{source.available ? 'Disponível' : outsideScope ? 'Fora da cobertura' : 'Indisponível'}</span><h3>{source.name} <ExternalLink size={14} /></h3><p>{source.scope}</p><small>{source.updated_at ? `Referência/atualização: ${source.updated_at}` : outsideScope ? 'Aplicável somente ao Brasil' : 'Sem atualização retornada'}{source.valid_from && source.valid_until ? ` · válido de ${source.valid_from} a ${source.valid_until}` : ''}{source.note ? ` · ${source.note}` : ''}</small></a> })}</div></section>
      <section className="challenge"><div><p className="eyebrow">Climazoide · ciência aberta</p><h2>Pesquisa reproduzível, produto compreensível.</h2><p>O projeto trabalha com previsão mensal M→M+1: para prever setembro, só podem ser usados dados disponíveis até agosto. O repositório de pesquisa registra os experimentos com PCA/PLS + LSTM, ConvLSTM, XGBoost, ONI e EDA. Nenhuma métrica experimental é apresentada como resultado de produção.</p></div><div className="challenge-numbers"><span><strong>78.561</strong> pontos/mês</span><span><strong>0,25°</strong> grade ERA5</span><span><strong>RMSE</strong> métrica de avaliação</span></div></section>
    </>}
    <footer><span>Climazoide · código e metodologia abertos</span><nav aria-label="Repositórios"><a href="https://github.com/SouBeatrizKaroline/Climazoide-Frontend" target="_blank" rel="noreferrer">Frontend</a><a href="https://github.com/SouBeatrizKaroline/Climazoide-Backend" target="_blank" rel="noreferrer">Backend</a><a href="https://github.com/mazeeqe/WORCAP-2026" target="_blank" rel="noreferrer">Repositório de pesquisa</a></nav><span>Dados meteorológicos possuem incerteza. Consulte alertas oficiais em situações críticas.</span></footer>
  </main>
}
